version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "com.google.dagger:dagger"
      - dependency-name: "com.google.dagger:dagger-producers"
      - dependency-name: "com.google.dagger:dagger-compiler"
      - dependency-name: "org.mockito:mockito-core"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
