#!/bin/sh

# rough

export PATH=$PATH:$JAVA_HOME/bin
base=`dirname $0`
export ALLOCATION_JAR=$base/lib/allocation.jar
exec java -cp $base/lib/caliper-@VERSION@.jar:$ALLOCATION_JAR:$CLASSPATH com.google.caliper.Runner $*

