#!/bin/sh
#
# Copyright (c) 2015 Google, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MYSELF=$(which "$0" 2>/dev/null)
[ $? -gt 0 ] && [ -f "$0" ] && MYSELF="./$0"
JAVA_CMD=java
[ -n "$JAVA_HOME" ] && JAVA_CMD="$JAVA_HOME/bin/java"
exec "$JAVA_CMD" $JAVA_ARGS -jar "$MYSELF" "$@"
exit 1
