name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Cancel in-progress runs for pull requests, but not for master branch pushes
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: "JDK ${{ matrix.java }}"
    strategy:
      matrix:
        java: [ 8, 11 ]
    runs-on: ubuntu-latest
    env:
      # Not actually used since we aren't building/testing the Android version,
      # but Maven still needs an absolute path or it complains.
      ANDROID_HOME: /
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Install'
        shell: bash
        run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn install -U -DskipTests=true -am -pl caliper
      - name: 'Test'
        shell: bash
        run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify -U -Dmaven.javadoc.skip=true -am -pl caliper
